name: Staging
on:
  push:
    branches:
    - staging
jobs:
  staging-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: update apt
      run: sudo apt-get update
    - name: Install git-ftp
      run: sudo apt-get -qq install git-ftp
    - name: Check ip
      run: wget -qO- https://ipecho.net/plain ; echo
    - name: Push to staging
      run: sudo git ftp init --force --user deployer@sbe.champresto.id --passwd ilovedeployer ftp://sbe.champresto.id
